version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 10

    commands:
        - cd $CODEBUILD_SRC_DIR
        - chmod 777 ./bin/split.sh
        - chmod 777 ./bin/splitsh-lite

  build:
    commands:
        - ./bin/split.sh
        - echo Finalizou OK