version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 10

    commands:
        #- git clone https://github.com/dflydev/git-subsplit.git
        #- cd git-subsplit
        #- ./install.sh

  build:
    commands:
        # Preparar diretorio para o split
        - echo Preparar diretorio para o SPLIT
        - cd $CODEBUILD_SRC_DIR
        - chmod 777 ./bin/split.sh
        - chmod 777 ./bin/splitsh-lite

        # Rodar o SPLIT
        - ./bin/split.sh

        - echo Finalizou OK