version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 10

    commands:
        #- git clone https://github.com/dflydev/git-subsplit.git
        #- cd git-subsplit
        #- ./install.sh

  build:
    commands:
        # Preparar diretorio para o split
        - cd $CODEBUILD_SRC_DIR

        # Rodar Split
        - git filter-branch --prune-empty --subdirectory-filter css/ main -f
        - git remote -v
        #- git filter-branch --subdirectory-filter css/ -f
        - git remote set-url origin https://$GIT_USER:$GIT_TOKEN@github.com/rhino-org/rhino.css.git
        #- git fetch origin
        - git remote -v
        - git push -u origin main        

        - echo Finalizou OK